version: 2

defaults: &defaults
  docker:
    - image: joatmon08/circleci-hashistack
  working_directory: /tmp/chrome-remote-desktop-pipeline
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: /home/circleci/key.json
    KEY_FINGERPRINT: 37b4ebf9245f06c2b1364c03a5a174aa
    INFRA_ENVIRONMENT: joatmon08

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: set up credentials
          command: make credentials
      - run:
          name: set up service account keys
          command: echo ${GCLOUD_SERVICE_KEY} > /home/circleci/key.json
      - run:
          name: push variables up to workspace
          command: bash ./scripts/pushvars.sh
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .terraformrc
            - key.json

  unit:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run some checks to ensure the infrastructure is ready to build
          command: make unit

  contract:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Run some checks to ensure the workspace has correct variables
          command: make contract

  plan:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: make init
      - run:
          name: Plan
          command: terraform plan

  apply:
    <<: *defaults
    steps:
      - add_ssh_keys:
          fingerprints:
            - "37:b4:eb:f9:24:5f:06:c2:b1:36:4c:03:a5:a1:74:aa"
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: make init
      - run:
          name: Apply
          command: terraform apply -auto-approve
      - run:
          name: Set up Chrome remote desktop
          command: make remote-desktop

  destroy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: make init
      - run:
          name: Apply
          command: terraform destroy --force

  stop:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: Initialize
          command: make init
      - run:
          name: Apply
          command: make stop

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - setup
      - stop:
          requires:
            - setup
          filters:
            branches:
              only: master
  remote-desktop:
    jobs:
      - setup
      - unit:
          requires:
            - setup
          filters:
            branches:
              only: master
      - contract:
          requires:
            - unit
          filters:
            branches:
              only: master
      - plan:
          requires:
            - contract
          filters:
            branches:
              only: master
      - apply:
          requires:
            - plan
          filters:
            branches:
              only: master
      - approve-destroy:
          type: approval
          requires:
            - plan
          filters:
            branches:
              only: master
      - destroy:
          requires:
            - approve-destroy
          filters:
            branches:
              only: master